import { AlignmentType, Document, Footer, Header, ImageRun, PageNumber, Paragraph, TextRun, type ParagraphChild } from 'docx'

const NAVY = '1E3A5F'
const disclaimer = 'Generated by AI from your resume and the job description. Check it for accuracy before you use it. Not a guarantee of interviews or job offers.'

async function logoRun(): Promise<ImageRun | null> {
  try { const response = await fetch('/talentseek-logo.png'); if (!response.ok) return null; return new ImageRun({ data: await response.arrayBuffer(), type: 'png', transformation: { width: 28, height: 28 } }) } catch { return null }
}

export async function brandedReportDocx(title: string, children: Paragraph[], extraDisclaimer?: string, preparedFor?: string): Promise<Document> {
  const logo = await logoRun()
  const generated = new Intl.DateTimeFormat(undefined, { year: 'numeric', month: 'long', day: 'numeric' }).format(new Date())
  const intro = [
    new Paragraph({ children: [new TextRun({ text: title, bold: true, color: NAVY, size: 36 })] }),
    ...(preparedFor ? [new Paragraph({ children: [new TextRun({ text: `Prepared for: ${preparedFor}`, color: '334155', size: 20 })] })] : []),
    new Paragraph({ spacing: { after: 240 }, children: [new TextRun({ text: `Generated: ${generated}`, color: '64748B', size: 18 })] }),
  ]
  const headerChildren: ParagraphChild[] = []
  if (logo) headerChildren.push(logo, new TextRun('  '))
  headerChildren.push(new TextRun({ text: title.toUpperCase(), bold: true, color: NAVY, size: 20 }))
  const footerLines = extraDisclaimer ? [extraDisclaimer, disclaimer] : [disclaimer]
  return new Document({ sections: [{ properties: { page: { margin: { top: 1000, bottom: 1100, left: 1080, right: 1080 } } }, headers: { default: new Header({ children: [new Paragraph({ children: headerChildren, border: { bottom: { color: NAVY, size: 6, space: 5, style: 'single' } } })] }) }, footers: { default: new Footer({ children: [...footerLines.map(line => new Paragraph({ children: [new TextRun({ text: line, size: 14, color: '64748B' })] })), new Paragraph({ alignment: AlignmentType.RIGHT, children: [new TextRun({ text: 'talentseek.ca   |   Page ', size: 16, color: '64748B' }), new TextRun({ children: [PageNumber.CURRENT], size: 16, color: '64748B' }), new TextRun({ text: ' of ', size: 16, color: '64748B' }), new TextRun({ children: [PageNumber.TOTAL_PAGES], size: 16, color: '64748B' })] })] }) }, children: [...intro, ...children] }] })
}

export { NAVY }
