'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'

type Job = { id: number; title: string; company: string; location: string; mode: 'Remote' | 'Hybrid' | 'On-site'; salary: string; posted: string; age: number; source: string; url: string; summary: string; skills: string[] }

const jobs: Job[] = [
  { id: 1, title: 'Senior Project Manager', company: 'Shopify', location: 'Toronto, ON', mode: 'Remote', salary: '$105k–$135k CAD', posted: 'Today', age: 0, source: 'Adzuna', url: 'https://www.shopify.com/careers', summary: 'Lead cross-functional programs that improve merchant experiences and internal operating systems.', skills: ['Program delivery', 'Stakeholder management', 'Agile'] },
  { id: 2, title: 'Product Operations Manager', company: 'Clio', location: 'Vancouver, BC', mode: 'Hybrid', salary: '$95k–$125k CAD', posted: '1 day ago', age: 1, source: 'Greenhouse', url: 'https://www.clio.com/careers/', summary: 'Improve product planning, launch operations, and the feedback loop between customers and product teams.', skills: ['Operations', 'Analytics', 'Product launches'] },
  { id: 3, title: 'Technical Program Manager', company: 'Hootsuite', location: 'Calgary, AB', mode: 'Remote', salary: '$100k–$130k CAD', posted: '2 days ago', age: 2, source: 'Lever', url: 'https://www.hootsuite.com/about/careers', summary: 'Coordinate technical initiatives across engineering, security, and business teams.', skills: ['Technical delivery', 'Risk management', 'Communication'] },
  { id: 4, title: 'Business Analyst', company: 'TELUS', location: 'Montreal, QC', mode: 'Hybrid', salary: '$75k–$95k CAD', posted: '3 days ago', age: 3, source: 'Adzuna', url: 'https://www.telus.com/en/careers', summary: 'Translate operational needs into clear requirements, reporting, and process improvements.', skills: ['SQL', 'Requirements', 'Process mapping'] },
  { id: 5, title: 'Customer Success Manager', company: 'Lightspeed', location: 'Ottawa, ON', mode: 'Remote', salary: '$80k–$105k CAD', posted: '5 days ago', age: 5, source: 'Greenhouse', url: 'https://www.lightspeedhq.com/careers/', summary: 'Partner with customers to drive adoption, renewals, and measurable business outcomes.', skills: ['Client strategy', 'SaaS', 'Renewals'] },
  { id: 6, title: 'Operations Coordinator', company: 'RBC', location: 'Toronto, ON', mode: 'On-site', salary: '$60k–$75k CAD', posted: '6 days ago', age: 6, source: 'Adzuna', url: 'https://jobs.rbc.com/ca/en', summary: 'Support business operations, reporting cadence, and cross-team coordination.', skills: ['Coordination', 'Reporting', 'Excel'] },
]

export default function JobSearchDemoPage() {
  const [query, setQuery] = useState('')
  const [location, setLocation] = useState('All Canada')
  const [mode, setMode] = useState('Any work style')
  const [recentOnly, setRecentOnly] = useState(false)
  const [saved, setSaved] = useState<number[]>([])
  const [selected, setSelected] = useState<Job | null>(null)
  const [signInPrompt, setSignInPrompt] = useState<{ job: Job; action: 'save' | 'apply' } | null>(null)

  useEffect(() => {
    const stored = sessionStorage.getItem('talentseek-pending-job-action')
    if (!stored) return
    sessionStorage.removeItem('talentseek-pending-job-action')
    const pending = JSON.parse(stored) as { jobId: number; action: 'save' | 'apply' }
    const job = jobs.find(item => item.id === pending.jobId)
    if (!job) return
    if (pending.action === 'apply') window.location.assign(job.url)
    else setSaved(current => current.includes(job.id) ? current : [...current, job.id])
  }, [])

  const filtered = useMemo(() => jobs.filter(job => {
    const words = `${job.title} ${job.company} ${job.skills.join(' ')}`.toLowerCase()
    return (!query || words.includes(query.toLowerCase())) && (location === 'All Canada' || job.location.includes(location)) && (mode === 'Any work style' || job.mode === mode) && (!recentOnly || job.age <= 2)
  }), [query, location, mode, recentOnly])

  const toggleSaved = (id: number) => setSaved(current => current.includes(id) ? current.filter(jobId => jobId !== id) : [...current, id])

  function continueToSignIn() {
    if (!signInPrompt) return
    sessionStorage.setItem('talentseek-pending-job-action', JSON.stringify({ jobId: signInPrompt.job.id, action: signInPrompt.action }))
    window.location.assign('/auth?next=%2Fjob-search-demo')
  }

  return <main className='min-h-screen bg-slate-50 px-6 py-10'><div className='mx-auto max-w-7xl'>
    <div className='flex flex-wrap items-center justify-between gap-3'><Link href='/dashboard' className='text-sm text-slate-500 hover:text-slate-700'>← Back to What would you like to do?</Link><Link href='/employer/jobs/new' className='rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50'>Hiring? Post a job</Link></div>
    <header className='mt-7 rounded-3xl bg-slate-900 px-7 py-10 text-white sm:px-10'><p className='text-sm font-semibold uppercase tracking-widest text-teal-300'>TalentSeek Jobs · Demo</p><h1 className='mt-3 text-3xl font-bold tracking-tight sm:text-5xl'>Find your next opportunity.</h1><p className='mt-4 max-w-2xl text-lg leading-8 text-slate-300'>A Canada-first job search experience that connects every listing to the employer’s original application page.</p><div className='mt-7 flex flex-wrap gap-3 text-sm'><span className='rounded-full bg-white/10 px-3 py-1.5'>Canadian opportunities</span><span className='rounded-full bg-white/10 px-3 py-1.5'>Direct employer links</span><span className='rounded-full bg-white/10 px-3 py-1.5'>{saved.length} saved jobs</span></div></header>

    <section className='-mt-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-lg'><div className='grid gap-3 lg:grid-cols-[1.5fr_1fr_1fr_auto]'><input value={query} onChange={event => setQuery(event.target.value)} placeholder='Search job title, company, or skill' aria-label='Search jobs' className='rounded-xl border border-slate-300 px-4 py-3 text-slate-900' /><select value={location} onChange={event => setLocation(event.target.value)} aria-label='Location' className='rounded-xl border border-slate-300 px-3 py-3 text-slate-900'><option>All Canada</option><option>Toronto, ON</option><option>Vancouver, BC</option><option>Calgary, AB</option><option>Montreal, QC</option><option>Ottawa, ON</option></select><select value={mode} onChange={event => setMode(event.target.value)} aria-label='Work style' className='rounded-xl border border-slate-300 px-3 py-3 text-slate-900'><option>Any work style</option><option>Remote</option><option>Hybrid</option><option>On-site</option></select><button onClick={() => { setQuery(''); setLocation('All Canada'); setMode('Any work style'); setRecentOnly(false) }} className='rounded-xl border border-slate-300 px-4 py-3 text-sm font-semibold text-slate-700 hover:bg-slate-50'>Clear filters</button></div><label className='mt-4 flex w-fit cursor-pointer items-center gap-2 text-sm text-slate-600'><input type='checkbox' checked={recentOnly} onChange={event => setRecentOnly(event.target.checked)} className='h-4 w-4 rounded border-slate-300 text-teal-700' /> Posted in the last 2 days</label></section>

    <div className='mt-10 grid gap-8 lg:grid-cols-[1fr_340px]'><section><div className='flex items-end justify-between'><div><p className='text-sm font-semibold text-teal-700'>{filtered.length} opportunities</p><h2 className='mt-1 text-2xl font-bold text-slate-900'>Jobs matching your search</h2></div><p className='text-sm text-slate-500'>Demo listings</p></div><div className='mt-5 space-y-4'>{filtered.map(job => <article key={job.id} className='rounded-2xl border border-slate-200 bg-white p-6 shadow-sm'><div className='flex flex-wrap items-start justify-between gap-4'><div><p className='text-sm font-semibold text-teal-700'>{job.company}</p><h3 className='mt-1 text-xl font-bold text-slate-900'>{job.title}</h3><p className='mt-1 text-sm text-slate-500'>{job.location} · {job.mode} · {job.posted}</p></div><button onClick={() => saved.includes(job.id) ? toggleSaved(job.id) : setSignInPrompt({ job, action: 'save' })} aria-label={`Save ${job.title}`} className={saved.includes(job.id) ? 'rounded-full bg-teal-700 px-3 py-1.5 text-sm font-semibold text-white' : 'rounded-full border border-slate-300 px-3 py-1.5 text-sm font-semibold text-slate-600 hover:bg-slate-50'}>{saved.includes(job.id) ? 'Saved ✓' : 'Save job'}</button></div><p className='mt-4 leading-7 text-slate-600'>{job.summary}</p><div className='mt-4 flex flex-wrap gap-2'>{job.skills.map(skill => <span key={skill} className='rounded-full bg-slate-100 px-3 py-1 text-xs font-medium text-slate-600'>{skill}</span>)}</div><div className='mt-5 flex flex-wrap items-center justify-between gap-3'><p className='font-semibold text-slate-900'>{job.salary}</p><div className='flex gap-3'><button onClick={() => setSelected(job)} className='text-sm font-semibold text-slate-700 underline'>View details</button><button onClick={() => setSignInPrompt({ job, action: 'apply' })} className='rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white hover:bg-slate-700'>Apply on employer site ↗</button></div></div></article>)}{filtered.length === 0 && <div className='rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-center text-slate-600'>No demo jobs match these filters. Try clearing a filter.</div>}</div></section>
      <aside className='space-y-5'><article className='rounded-2xl border border-teal-100 bg-teal-50 p-6'><p className='text-xs font-semibold uppercase tracking-wider text-teal-800'>How this will work</p><h2 className='mt-2 text-xl font-bold text-slate-900'>Direct, current opportunities</h2><ol className='mt-4 space-y-3 text-sm leading-6 text-slate-700'><li><strong>1.</strong> Search jobs from approved sources and TalentSeek employers.</li><li><strong>2.</strong> Save a role to your TalentSeek dashboard.</li><li><strong>3.</strong> Tailor a saved resume for that job.</li><li><strong>4.</strong> Apply on the employer’s original site.</li></ol></article><article className='rounded-2xl border border-slate-200 bg-white p-6 shadow-sm'><p className='text-xs font-semibold uppercase tracking-wider text-slate-500'>Data source</p><p className='mt-2 font-semibold text-slate-900'>Jobs by Adzuna · direct employer feeds · TalentSeek postings</p><p className='mt-2 text-sm leading-6 text-slate-600'>Employer-submitted roles are reviewed before they appear publicly and always link to the employer’s application page.</p></article></aside>
    </div>
    {selected && <div role='dialog' aria-modal='true' aria-label={selected.title} className='fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-6'><article className='w-full max-w-2xl rounded-2xl bg-white p-7 shadow-xl'><div className='flex items-start justify-between gap-5'><div><p className='font-semibold text-teal-700'>{selected.company}</p><h2 className='mt-1 text-2xl font-bold text-slate-900'>{selected.title}</h2><p className='mt-2 text-slate-500'>{selected.location} · {selected.mode} · {selected.posted}</p></div><button onClick={() => setSelected(null)} className='rounded-lg px-3 py-2 text-sm text-slate-600 hover:bg-slate-100'>Close</button></div><p className='mt-6 leading-7 text-slate-700'>{selected.summary}</p><h3 className='mt-6 font-semibold text-slate-900'>What to highlight in your application</h3><ul className='mt-3 list-disc space-y-2 pl-5 text-slate-600'>{selected.skills.map(skill => <li key={skill}>{skill}</li>)}</ul><div className='mt-7 flex justify-end gap-3'><button onClick={() => saved.includes(selected.id) ? toggleSaved(selected.id) : setSignInPrompt({ job: selected, action: 'save' })} className='rounded-xl border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700'>{saved.includes(selected.id) ? 'Remove saved job' : 'Save job'}</button><button onClick={() => setSignInPrompt({ job: selected, action: 'apply' })} className='rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white'>Apply on employer site ↗</button></div></article></div>}
    {signInPrompt && <div role='dialog' aria-modal='true' aria-label='Sign in to continue' className='fixed inset-0 z-[60] flex items-center justify-center bg-slate-950/50 p-6'><article className='w-full max-w-md rounded-2xl bg-white p-7 shadow-xl'><p className='text-sm font-semibold uppercase tracking-wider text-teal-700'>TalentSeek account</p><h2 className='mt-2 text-2xl font-bold text-slate-900'>{signInPrompt.action === 'save' ? 'Save this job to your dashboard' : 'Sign in to continue to the employer site'}</h2><p className='mt-3 leading-7 text-slate-600'>Create a free account to {signInPrompt.action === 'save' ? 'track this role and tailor your resume later.' : `continue your application for ${signInPrompt.job.title} at ${signInPrompt.job.company}.`}</p><div className='mt-7 flex justify-end gap-3'><button onClick={() => setSignInPrompt(null)} className='rounded-xl px-4 py-2 text-sm font-semibold text-slate-600'>Not now</button><button onClick={continueToSignIn} className='rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white'>Sign in or create account</button></div></article></div>}
  </div></main>
}
